### ISSUE TITLE
[EPIC] <Title of Epic>

### ISSUE THREAD

**Issue by noahumbra** [noahumbra/blog_final#20]
### Milestone

**Milestone:** [link to milestone]
Add a few sentences to describe the milestone.

# Epic: Epic Name

### Overview

- List item
- List item

### Tasks

Use the following checklist to ensure each epic is built out properly. If needed, you can add or remove items.
- [ ] Pull together initial list of relevant user stories for this epic
- [ ] Make a list of the content requirements for this epic
- [ ] Make a list of the technical requirements for this epic
- [ ] Post current wireframe and mock-upss
- [ ] Review wireframes and mock-ups with FEWD, BEWD, Data, SBL Help, Content team members
- [ ] Refine user stories to prepare for development phase
- [ ] Identify and capture tasks for user testing
- [ ] Conduct user testing

### User stories

<hr>
### MVP (Beta release)
- Story (link)
- Story (link)

### Backlog (post-MVP)
- Story (link)

### Technical
- List item
- List item

### Content
- Link item
- Link item

### Task ideation
- Add here

#### Updated: MM/DD/YYYY

| Page name | Page name | Page name |
|------------|------------|------------|
|![Image](Link)|![Image](Link)|![Image](Link)|
